import type { Graph, Run } from './schema';
import { ensureGraphEdgeMetadata } from './edge-metadata';

const escape = (v: unknown) => String(v ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
const md = (v: string) => v.replaceAll('|', '\\|').replaceAll('\n', ' ');
export function renderMarkdown(run: Run, graph: Graph) {
  ensureGraphEdgeMetadata(graph);
  const name = (id: string) => graph.nodes.find(n => n.id === id)?.label ?? id;
  return `# ${md(run.product)} — supply evidence\n\nMode: **${run.mode}** · Status: ${run.status} · Stop: ${run.stop_reason ?? 'running'} · Revision: ${graph.revision}\n\n${run.mode === 'replay' ? 'CURATED REPLAY: hand-authored model results over short source excerpts; not live research.\n\n' : ''}| From | Relation | To | Support | Scope | Source URLs | Recorded UTC | Confidence (0–1) | Claim IDs |\n| --- | --- | --- | --- | --- | --- | --- | --- | --- |\n${graph.edges.map(e => `| ${md(name(e.source_node_id))} | ${e.predicate} | ${md(name(e.target_node_id))} | ${e.support_label} | ${e.scope.type} | ${e.source.map(s => md(s.url)).join('; ')} | ${e.date ?? 'unknown'} ${e.time ?? ''} | ${e.confidence.toFixed(2)} (edge_evidence_v1) | ${e.claim_ids.join(', ')} |`).join('\n')}\n\nConfidence is a heuristic evidence score, not a calibrated probability. Date/time records the latest evidence observation in UTC; publication dates remain on each source. Full score factors are in graph.json.\n\n## Evidence\n\n${graph.claims.map(c => `### ${c.id}\n\n${md(name(c.subject_id))} → ${c.predicate} → ${md(name(c.object_id))}\n\n${c.rationale}\n\n${c.evidence.map(e => `> ${e.span.replaceAll('\n', '\n> ')}\n\nSource: ${graph.sources.find(s => s.id === e.source_id)?.url}\n\nLocator: \`${e.locator}\` · ${e.support_type}`).join('\n\n')}\n`).join('\n')}\n## Open questions\n\n${run.open_questions.map(q => `- ${q}`).join('\n')}\n`;
}
export function renderHtml(run: Run, graph: Graph) {
  ensureGraphEdgeMetadata(graph);
  const name = (id: string) => graph.nodes.find(n => n.id === id)?.label ?? id;
  const maxTier = graph.stats.max_tier;
  const columns = [...new Set(graph.nodes.map(n => n.tier ?? maxTier + 1))].sort((a, b) => b - a);
  const positions = new Map<string, { x: number; y: number }>();
  for (const [col, tier] of columns.entries()) graph.nodes.filter(n => (n.tier ?? maxTier + 1) === tier).forEach((n, row) => positions.set(n.id, { x: 30 + col * 290, y: 55 + row * 115 }));
  const height = Math.max(240, ...[...positions.values()].map(p => p.y + 125));
  const width = Math.max(720, columns.length * 290);
  const svg = `<svg role="img" aria-label="Directed supply evidence graph" width="${width}" height="${height}" viewBox="0 0 ${width} ${height}"><defs><marker id="arrow" markerWidth="8" markerHeight="8" refX="7" refY="4" orient="auto"><path d="M0,0 L8,4 L0,8" fill="#66809b"/></marker></defs>${graph.edges.map((e, i) => {
    const a = positions.get(e.source_node_id)!; const b = positions.get(e.target_node_id)!;
    const startX = a.x + 215; const endX = b.x - 7;
    const sy = a.y + 31; const ey = b.y + 31; const bend = a.x === b.x ? 70 + i * 4 : 30;
    return `<a href="#${escape(e.id)}"><path d="M${startX},${sy} C${startX + bend},${sy} ${endX - bend},${ey} ${endX},${ey}" fill="none" stroke="${e.support_label === 'disputed' ? '#c33d48' : '#66809b'}" stroke-width="2" ${e.support_label === 'user_asserted' ? 'stroke-dasharray="6 4"' : ''} marker-end="url(#arrow)"/><text x="${(startX + endX) / 2}" y="${(sy + ey) / 2 - 8}" text-anchor="middle" font-size="10" fill="#345">${i + 1}. ${escape(e.predicate)}</text><title>${escape(name(e.source_node_id))} ${escape(e.predicate)} ${escape(name(e.target_node_id))}</title></a>`;
  }).join('')}${graph.nodes.map(n => {
    const p = positions.get(n.id)!; const lines = n.label.match(/.{1,25}(?:\s|$)|.{1,25}/g)?.slice(0, 2) ?? [n.label];
    return `<g><title>${escape(n.label)} · ${escape(n.kind)} · ${escape(n.id)}</title><rect x="${p.x}" y="${p.y}" width="215" height="78" rx="9" fill="${n.id === graph.root_node_id ? '#e1f3ed' : '#fff'}" stroke="#b2c2ce"/><text x="${p.x + 12}" y="${p.y + 21}" font-size="13" font-weight="600">${lines.map((line, i) => `<tspan x="${p.x + 12}" dy="${i ? 16 : 0}">${escape(line.trim())}</tspan>`).join('')}</text><text x="${p.x + 12}" y="${p.y + 64}" font-size="10" fill="#657789">${escape(n.kind)} · ${n.tier === null ? 'context' : `tier ${n.tier}`}</text></g>`;
  }).join('')}</svg>`;
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Security-Policy" content="default-src 'none'; style-src 'unsafe-inline'; img-src data:; base-uri 'none'; form-action 'none'"><title>${escape(run.product)} — evidence inspector</title><style>
  *{box-sizing:border-box}body{margin:0;background:#f3f6f8;color:#172c3f;font:15px/1.55 system-ui,sans-serif}main{max-width:1250px;margin:auto;padding:36px 24px}h1{font-size:30px;letter-spacing:-1px;margin:0 0 8px}h2{margin-top:28px;font-size:20px}a{color:#155b85}small,.muted{color:#576f80}code{font-size:11px;overflow-wrap:anywhere}.banner{padding:13px 18px;background:#fff0cc;border:1px solid #e9ca7d;border-radius:8px;margin:18px 0}.card{background:white;border:1px solid #dce4e9;border-radius:12px;padding:20px;margin:14px 0;scroll-margin-top:12px}.graph{overflow:auto;padding:10px}svg{font-family:system-ui}table{border-collapse:collapse;width:100%;font-size:13px}td,th{padding:10px;text-align:left;border-bottom:1px solid #e4ebef;vertical-align:top}blockquote{margin:12px 0;padding:12px 18px;background:#eff5f8;border-left:3px solid #5e91ac;white-space:pre-wrap}summary{cursor:pointer;font-weight:600}.badge{display:inline-block;background:#e7eff4;border-radius:4px;font-size:12px;padding:2px 7px;margin-right:5px}.disputed{background:#ffe1e1}.metadata{display:flex;flex-wrap:wrap;gap:8px 20px}.questions li{margin-bottom:7px}.edge-title{font-weight:700;font-size:17px}.sources p{margin:4px 0}:target{outline:3px solid #5b9fa1}.overflow{overflow:auto}
  </style></head><body><main><p class="muted">SUPPLY CHAIN OSINT · LOCAL DEBUG INSPECTOR</p><h1>${escape(run.product)}</h1><div class="metadata"><span>${graph.nodes.length} nodes · ${graph.edges.length} edges · ${graph.claims.length} claims</span><span>Revision ${graph.revision}</span><span>Status: <b>${run.status}</b> · ${escape(run.stop_reason ?? 'in progress')}</span></div>${run.mode === 'replay' ? '<div class="banner"><b>CURATED REPLAY</b> — short public-source excerpts and hand-authored model outputs. No fresh web research or live model verification occurred.</div>' : ''}<p class="muted">Follow arrows from input/manufacturer to output. Click a numbered relationship for its evidence. Context nodes have no evidenced upstream dependency tier. Refresh this file during a run to see its latest committed findings.</p><div class="card graph">${svg}</div><h2>Relationships</h2><div class="card overflow"><table><thead><tr><th>#</th><th>From → relation → to</th><th>Support</th><th>Scope</th><th>Confidence (0–1)</th><th>Recorded UTC</th></tr></thead><tbody>${graph.edges.map((e, i) => `<tr><td><a href="#${e.id}">${i + 1}</a></td><td>${escape(name(e.source_node_id))} → <b>${e.predicate}</b> → ${escape(name(e.target_node_id))}</td><td>${e.support_label}</td><td>${e.scope.type}</td><td>${e.confidence.toFixed(2)}</td><td>${escape(e.date)} ${escape(e.time)}</td></tr>`).join('')}</tbody></table></div>${graph.edges.map((e, i) => `<section id="${e.id}" class="card"><p class="edge-title">${i + 1}. ${escape(name(e.source_node_id))} → ${e.predicate} → ${escape(name(e.target_node_id))}</p><span class="badge ${e.support_label === 'disputed' ? 'disputed' : ''}">${e.support_label}</span><span class="badge">${e.scope.type} scope</span><span class="badge">Confidence ${e.confidence.toFixed(2)} / 1</span><p class="muted">Recorded UTC: ${escape(e.date)} ${escape(e.time)} · ${e.source.length} source(s)</p><details><summary>Confidence calculation · ${escape(e.confidence_details.method.name)}</summary><p>Heuristic evidence score, not a calibrated probability.</p><pre><code>${escape(JSON.stringify(e.confidence_details.factors, null, 2))}</code></pre>${e.confidence_details.data_quality.notes.map(note => `<p class="muted">${escape(note)}</p>`).join('')}</details><p>${escape(e.rationale)}</p>${Object.keys(e.data.custom).length ? `<details><summary>Imported BOM provenance (unverified)</summary><pre><code>${escape(JSON.stringify(e.data.custom, null, 2))}</code></pre></details>` : ''}${e.caveats.map(c => `<p class="muted">${escape(c)}</p>`).join('')}${e.claim_ids.map(cid => graph.claims.find(c => c.id === cid)!).map(c => `<details open><summary>${c.evidence[0]?.support_type === 'contradicts' ? 'Contrary evidence' : 'Evidence'} · ${c.support_label}</summary><p><code>${escape(c.id)}</code></p>${c.evidence.map(ev => {
    const source = graph.sources.find(s => s.id === ev.source_id)!;
    const link = /^https?:\/\//.test(source.url) ? `<a href="${escape(source.url)}" target="_blank" rel="noopener noreferrer">${escape(source.title ?? source.url)}</a>` : escape(source.title ?? source.url);
    return `<blockquote>${escape(ev.span)}</blockquote><div class="sources"><p>${link}</p><p>Publisher: ${escape(source.publisher ?? 'unknown')} · Published: ${escape(source.published_at ?? 'unknown')} · Retrieved: ${escape(source.retrieved_at)}</p><p>Polarity: <b>${ev.support_type}</b> · <code>${escape(ev.locator)}</code></p><p><code>${escape(source.content_hash)}</code></p></div>`;
  }).join('')}<p class="muted">${c.resolution_notes.map(escape).join(' ')}</p></details>`).join('')}</section>`).join('')}<h2>Open questions and limits</h2><div class="card"><ul class="questions">${run.open_questions.map(q => `<li>${escape(q)}</li>`).join('')}</ul><p>${run.usage.searches} searches · ${run.usage.documents} fetch attempts · ${run.usage.model_calls} model calls · ${run.usage.input_tokens + run.usage.output_tokens} observed tokens · ${run.usage.cost_minor} USD cents reserved</p><p class="muted">${escape(run.usage.cost_method)}</p></div><p class="muted">Run <code>${run.id}</code> · Graph <code>${graph.id}</code><br>Exported ${escape(graph.exported_at)}. Full claims, including negative-only findings, are in graph.json; operational decisions are in history.jsonl.</p></main></body></html>`;
}
